// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Audi_UX1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
LV_EVENT_GET_COMP_CHILD = lv_event_register_id();
ui_Screen2_screen_init();
}

void ui_destroy( void )
{
    ui_Screen2_screen_destroy();
}
