// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Audi_UX1

#ifndef _AUDI_UX1_UI_H
#define _AUDI_UX1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen2.h"
#include "ui_Screen4.h"

///////////////////// VARIABLES ////////////////////

// FONTS
LV_FONT_DECLARE( ui_font_FontLarge);
LV_FONT_DECLARE( ui_font_FontVeryVeryLarge);
LV_FONT_DECLARE( ui_font_FontVeryLarge);
LV_IMG_DECLARE( ui_img_logo_de_audi__png);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
