// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Audi_UX1

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// Temperature slider configuration
#define UI_TEMP_MIN_TENTHS   150  // 15.0°C
#define UI_TEMP_MAX_TENTHS   270  // 27.0°C
#define UI_TEMP_STEP_TENTHS  5    // 0.5°C steps
#define UI_TEMP_ARC_STEPS    ((UI_TEMP_MAX_TENTHS - UI_TEMP_MIN_TENTHS) / UI_TEMP_STEP_TENTHS)
#define UI_TEMP_DEFAULT_TENTHS 210 // 21.0°C

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_TempSlider;
extern lv_obj_t *ui_TempIn;
extern lv_obj_t *ui_Outside;
extern lv_obj_t *ui_TempOut;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
