// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Audi_UX1

#include "ui.h"

static void temp_slider_update_label(int position)
{
    if (!ui_TempIn) {
        return;
    }
    if (position <= 0) {
        lv_label_set_text(ui_TempIn, "LO");
        return;
    }
    if (position >= UI_TEMP_ARC_STEPS) {
        lv_label_set_text(ui_TempIn, "HI");
        return;
    }

    int temp_tenths = UI_TEMP_MIN_TENTHS + position * UI_TEMP_STEP_TENTHS;
    char buf[8];
    if (temp_tenths % 10 == 0) {
        lv_snprintf(buf, sizeof(buf), "%d°", temp_tenths / 10);
    } else {
        lv_snprintf(buf, sizeof(buf), "%d.%d°", temp_tenths / 10, temp_tenths % 10);
    }
    lv_label_set_text(ui_TempIn, buf);
}

static void temp_slider_event_cb(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_VALUE_CHANGED) {
        return;
    }
    lv_obj_t * slider = lv_event_get_target(e);
    temp_slider_update_label(lv_arc_get_value(slider));
}

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_TempSlider = NULL;lv_obj_t *ui_TempIn = NULL;lv_obj_t *ui_Outside = NULL;lv_obj_t *ui_TempOut = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempSlider = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_TempSlider, 350);
lv_obj_set_height( ui_TempSlider, 350);
lv_obj_set_align( ui_TempSlider, LV_ALIGN_CENTER );
lv_arc_set_range(ui_TempSlider, 0, UI_TEMP_ARC_STEPS);
lv_arc_set_value(ui_TempSlider, (UI_TEMP_DEFAULT_TENTHS - UI_TEMP_MIN_TENTHS) / UI_TEMP_STEP_TENTHS);
lv_obj_add_event_cb(ui_TempSlider, temp_slider_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

ui_TempIn = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_TempIn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempIn, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TempIn, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempIn,"21°");
lv_obj_set_style_text_color(ui_TempIn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempIn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempIn, &ui_font_FontVeryVeryLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Outside = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Outside, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Outside, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Outside, 2 );
lv_obj_set_y( ui_Outside, 134 );
lv_obj_set_align( ui_Outside, LV_ALIGN_CENTER );
lv_label_set_text(ui_Outside,"OUTSIDE");
lv_obj_set_style_text_color(ui_Outside, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Outside, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Outside, &ui_font_FontLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempOut = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_TempOut, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempOut, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempOut, 7 );
lv_obj_set_y( ui_TempOut, 187 );
lv_obj_set_align( ui_TempOut, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempOut,"-5°");
lv_obj_set_style_text_color(ui_TempOut, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempOut, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempOut, &ui_font_FontVeryLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

temp_slider_update_label(lv_arc_get_value(ui_TempSlider));

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_TempSlider= NULL;
ui_TempIn= NULL;
ui_Outside= NULL;
ui_TempOut= NULL;

}
